### ISSUE TITLE
FrameBufferConv methods are unsound

### ISSUE THREAD

**Issue by nox** [rust-av/rust-av#40]
In the `as_slice` and `as_slice_mut` methods, nothing checks that `T` can actually be read from arbitrary bytes, so one could implement the `FrameBufferConv<T>` for arbitrary `T` types and undefined behaviour would happen.

**Comment by lu-zero** [comment]
I could not find a good way to express that specific constraint, if you have an idea I'm all ears :)

**Comment by emilio** [comment]
Probably `T: Copy` is at least a good aproximation

**Comment by nox** [comment]
If you can't find a good way to express that specific constraint, then that method should be unsafe.

A `Copy` type does not necessarily accept all bit representations, so this would still be unsound. For example, `bool` is `Copy` but only 2 values are valid for it, out of the 256 values possible for `u8`.

**Comment by lu-zero** [comment]
I explicitly restricted the trait to only the supported types.

**Comment by nox** [comment]
It is still unsafe, the transmuted pointer's alignment is not checked. `f32` and `i16` have higher alignment requirements than `u8`.

**Comment by lu-zero** [comment]
The underlying buffer is aligned to 32bytes.

**Comment by sdroege** [comment]
The trait should just be `unsafe`, no need to seal it. Usage of the API would be safe, as expected, but whenever someone wants to implement the trait it has to be `unsafe`.

Same situation as with the `Sync` and `Send` traits. Whenever implementing the traits you need to know what you're doing and thus mark it as `unsafe`, otherwise all kinds of bad things will happen. But usage of the traits is safe.
