### ISSUE TITLE
Write more well known Formatons/Sonitons

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#47]
- [x] Write higher bitdepth YUV Formatons
- [x] Write 420 and 444 YUV Formatons
- [x] Write higher bitdepth RGB Formatons

- [x] Write the F64 Soniton
- [x] Write the S32 Soniton

**Comment by osman-turan** [comment]
Thanks @lu-zero for reviewing of my PR: #179! 🙌 I think, "Write higher bitdepth RGB Formatons" task should be completed. If you think we need to add more higher depth RGB formatons, please let me know. Otherwise, this issue can be closed. Because both [F64](https://github.com/rust-av/rust-av/blob/6c5ba50050660caa92537ecc2385d4692b84b99a/data/src/audiosample.rs#L353-L361) and [S32](https://github.com/rust-av/rust-av/blob/6c5ba50050660caa92537ecc2385d4692b84b99a/data/src/audiosample.rs#L333-L341) appears to be implemented already.

**Comment by Luni-4** [comment]
Thank you @osman-turan! We can close this issue
